from datetime import UTC, datetime

DEFAULT_PRESET_UPDATED_AT: datetime = datetime(2026, 8, 24, tzinfo=UTC)

DEFAULT_PRESETS: list[dict[str, object]] = [
    {
        "name": "default",
        "default": True,
        "cli": "--socket-timeout 30 --download-archive %(archive_file)s",
        "description": "Downloads the best video and audio quality selected by yt-dlp.",
        "folder": "",
        "template": "",
        "cookies": "",
        "priority": 0,
        "updated_at": DEFAULT_PRESET_UPDATED_AT,
    },
    {
        "name": "mobile",
        "cli": '--socket-timeout 30 --download-archive %(archive_file)s\n-t mp4 --merge-output-format mp4 --add-chapters --remux-video mp4 \n--embed-metadata --embed-thumbnail \n--postprocessor-args "-movflags +faststart"',
        "default": True,
        "description": "Downloads the best video and audio quality in MP4, then adds chapters, metadata, and a thumbnail for mobile devices.",
        "folder": "",
        "template": "",
        "cookies": "",
        "priority": 0,
        "updated_at": DEFAULT_PRESET_UPDATED_AT,
    },
    {
        "name": "1080p",
        "cli": "--socket-timeout 30 --download-archive %(archive_file)s\n-S vcodec:h264 --format 'bv[height<=1080][ext=mp4]+ba[ext=m4a]/b[ext=mp4]/b[ext=webm]'",
        "default": True,
        "description": "Downloads the best video and audio quality in MP4 at up to 1080p.",
        "folder": "",
        "template": "",
        "cookies": "",
        "priority": 0,
        "updated_at": DEFAULT_PRESET_UPDATED_AT,
    },
    {
        "name": "720p",
        "cli": "--socket-timeout 30 --download-archive %(archive_file)s\n-S vcodec:h264 --format 'bv[height<=720][ext=mp4]+ba[ext=m4a]/b[ext=mp4]/b[ext=webm]'",
        "default": True,
        "description": "Downloads the best video and audio quality in MP4 at up to 720p.",
        "folder": "",
        "template": "",
        "cookies": "",
        "priority": 0,
        "updated_at": DEFAULT_PRESET_UPDATED_AT,
    },
    {
        "name": "audio_only",
        "cli": "--socket-timeout 30 --download-archive %(archive_file)s\n--extract-audio --add-chapters --embed-metadata --embed-thumbnail --format 'bestaudio/best'",
        "default": True,
        "description": "Downloads audio only, then adds chapters, metadata, and a thumbnail.",
        "folder": "",
        "template": "",
        "cookies": "",
        "priority": 0,
        "updated_at": DEFAULT_PRESET_UPDATED_AT,
    },
    {
        "name": "info_reader_plugin",
        "description": "Uses a predictable filename layout and metadata for yt-dlp info-reader plugins in Jellyfin, Emby, Plex, and WatchState.",
        "folder": "",
        "template": "%(channel)s [%(channel_id|Unknown_id)s]/Season %(release_date>%Y,upload_date>%Y|Unknown)s/%(release_date>%Y%m%d,upload_date>%Y%m%d)s - %(title).180B [%(id)s].%(ext)s",
        "cli": "--socket-timeout 30 --download-archive %(archive_file)s\n--windows-filenames --write-info-json --embed-info-json \n--convert-thumbnails jpg --write-thumbnail --embed-metadata",
        "cookies": "",
        "default": True,
        "priority": 0,
        "updated_at": DEFAULT_PRESET_UPDATED_AT,
    },
    {
        "name": "nfo_maker_tv",
        "description": "Generates a filename layout and metadata for Jellyfin, Emby, and Plex episodes.",
        "folder": "",
        "template": "%(channel)s [%(channel_id|Unknown_id)s]/Season %(release_date>%Y,upload_date>%Y|Unknown)s/S%(release_date>%Y,upload_date>%Y)sE%(release_date>%m%d,upload_date>%m%d)s - %(title).100B [%(id)s].%(ext)s",
        "cli": '--socket-timeout 30 --download-archive %(archive_file)s\n--use-postprocessor "NFOMakerPP:when=after_move" \n--windows-filenames --convert-thumbnails jpg --write-thumbnail',
        "cookies": "",
        "default": True,
        "priority": 0,
        "updated_at": DEFAULT_PRESET_UPDATED_AT,
    },
    {
        "name": "nfo_maker_movie",
        "description": "Generates a filename layout and metadata for Jellyfin, Emby, and Plex movies.",
        "folder": "",
        "template": "%(channel)s [%(channel_id|Unknown_id)s]/Season %(release_date>%Y,upload_date>%Y|Unknown)s/S%(release_date>%Y,upload_date>%Y)sE%(release_date>%m%d,upload_date>%m%d)s - %(title).100B [%(id)s].%(ext)s",
        "cli": '--socket-timeout 30 --download-archive %(archive_file)s\n--use-postprocessor "NFOMakerPP:when=after_move;mode=movie" \n--windows-filenames --convert-thumbnails jpg --write-thumbnail',
        "cookies": "",
        "default": True,
        "priority": 0,
        "updated_at": DEFAULT_PRESET_UPDATED_AT,
    },
    {
        "name": "generic_browser",
        "default": True,
        "cli": '--socket-timeout 30 --download-archive %(archive_file)s --use-extractors "generic"',
        "description": "Use the bundled generic browser extractor with the endpoint configured by YTP_BROWSER_URL.",
        "folder": "",
        "template": "",
        "cookies": "",
        "priority": 0,
        "updated_at": DEFAULT_PRESET_UPDATED_AT,
    },
]
